### ISSUE TITLE
Can you compile to binary file in Release page?

### ISSUE THREAD

**Issue by TangMonk** [Rapiz1/DungeonRush#1]
Download dependices and compile is inconvenient

**Comment by yujqiao** [comment]
Linux and Windows releases are provided.
Are you using OS X? I don't have a Mac to compile it. But if you have `brew` installed on your computer, it should be easy to install the dependencies by `brew`

**Comment by TangMonk** [comment]
> Linux and Windows releases are provided.
> Are you using OS X? I don't have a Mac to compile it. But if you have `brew` installed on your computer, it should be easy to install the dependencies by `brew`

sorry, my mistake
