### ISSUE TITLE
AppImage crashs when creating data file

### ISSUE THREAD

**Issue by yujqiao** [Rapiz1/DungeonRush#14]
Found by @BruceZhang1993
AppImage will crash when one turn is finished, creating the data file `storage.dat`. 
@probonopd The path used in the code is `./storage.dat`.
Anyway the data should be held in `$HOME` or something. I just don't want to get into a tricky situation related to the platforms. Is there a solution that the program can write into the working directory?

**Comment by yujqiao** [comment]
With https://github.com/Rapiz1/DungeonRush/commit/3b0a11183cc8f9747de52182360d4faed331cb4b the storage will be disabled if the file descriptor can't be opened, so the program won't crash anymore.
It does not really hurt if the rank list can't persist.

**Comment by probonopd** [comment]
> Anyway the data should be held in `$HOME` or something. 

Yes, this is the way to go. Then the problem will go away.

**Comment by yujqiao** [comment]
Resolved by 3b0a11183cc8f9747de52182360d4faed331cb4b
