### ISSUE TITLE
Migrate to CMake

### ISSUE THREAD

**Issue by yujqiao** [Rapiz1/DungeonRush#20]
This project is cross-platform but the build system `make` adds to the difficulty of compiling it against different platforms. CMake may be the answer.
There has been some effort like https://github.com/Rapiz1/DungeonRush/pull/7

**Comment by yujqiao** [comment]
Added in https://github.com/Rapiz1/DungeonRush/pull/22

**Comment by vaguerant** [comment]
The required cmake version seems to be incorrect in your `CMakeLists.txt`. You're using the `DESCRIPTION` tag added in cmake 3.8, but reporting 3.5.1 as the minimum version. On my (very outdated) Raspbian system, the repos only provide up to cmake 3.7.2, so I'm not able to compile the app unmodified. Removing the `DESCRIPTION` tag entirely allows the app to build.

I didn't figure any of this out myself, just Googled and found somebody else with the same issue on another project: https://github.com/The-OpenROAD-Project/OpenDB/issues/80

At that point I'm still not able to run the app, with it throwing the following error:
```
Renderer could not be created! SDL Error: Couldn't find matching render driver
Failed to initialize!
```
But I'm content to put that down to me having no idea what I'm doing, I don't think me not getting it running necessarily means there's anything wrong with it.

**EDIT:** After some more Googling, I think I need to run SDL2 apps from the terminal, not the desktop, so in case it's helpful, here's the output when running from terminal:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Unable to create texture from res/drawable/title.png! SDL Error: Texture dimensions are limited to 2048x2048
Failed to load media!
```

**EDIT2:** I know I'm getting very off-topic at this point, sorry. After manually editing the title screen to get it down under the 2048 limit on Raspberry Pi (1932-wide, 7 frames--I edited the text file as well), I am able to boot and play the game. However, I think it may be running at the wrong resolution. Things like the title and pause screens appear to be centered for about 720p, but the game is running at 1080p on my end. It's also very slow, but that may just be down to the weak CPU in the Raspberry Pi. Still, it works! Building on Pi via cmake is functional as long as you can either get >3.8 or edit out the `DESCRIPTION` string, then make a minor title screen edit.
