### ISSUE TITLE
I ported your game to Android platform. I created a new github project to show this Android version and name the source. Would you allow me to do this?

### ISSUE THREAD

**Issue by imrunning** [Rapiz1/DungeonRush#33]

**Comment by yujqiao** [comment]
Sure. That's how open source works.And I will appreciate it if you could put a link to this project.

**Comment by imrunning** [comment]
> Sure. That's how open source works.And I will appreciate it if you could put a link to this project.

I uploaded this project a few minutes ago.  https://github.com/imrunning/DungeonRush_Android

**Comment by yujqiao** [comment]
@imrunning Great. However you need to add [GPL3](https://github.com/Rapiz1/DungeonRush/blob/master/LICENSE) license to your project.

**Comment by imrunning** [comment]
> @imrunning Great. However you need to add [GPL3](https://github.com/Rapiz1/DungeonRush/blob/master/LICENSE) license to your project.

Done.

**Comment by imrunning** [comment]
> @imrunning Great. However you need to add [GPL3](https://github.com/Rapiz1/DungeonRush/blob/master/LICENSE) license to your project.

Done

**Comment by yujqiao** [comment]
I added a link in README to your port! Thanks!
